/* Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved. */
/* SPDX-License-Identifier: MIT-0 */

const aboutModalData = {
	ABOUT: {
		VERSION: "Version",
		VERSION_VALUE: "1.0.0",
		BUILD: "",
		COPYRIGHT: "ABOUT_MODAL.ABOUT.COPYRIGHT"
	},
	TERMS: {
		TERMS_PREFIX: "ABOUT_MODAL.TERMS.PREFIX",
		TERMS_LINK_LABEL: "ABOUT_MODAL.TERMS.LINK_LABEL",
		TERMS_SUFFIX: "ABOUT_MODAL.TERMS.SUFFIX"
	},
	ATTRIBUTIONS: {
		PARTNER_ATTRIBUTION_TITLE: "ABOUT_MODAL.ATTRIBUTIONS.PA_TITLE",
		SOFTWARE_ATTRIBUTION_TITLE: "ABOUT_MODAL.ATTRIBUTIONS.SA_TITLE",
		SOFTWARE_ATTRIBUTION_DESC: "ABOUT_MODAL.ATTRIBUTIONS.SA_DESC"
	}
};

export default aboutModalData;
