import appConfig from "./appConfig";

const {
	LINKS: { AWS_CUSTOMER_AGREEMENT, AWS_ACCEPTABLE_USE_POLICY, AWS_PRIVACY_NOTICE, AMAZON_LOCATION_TERMS_AND_CONDITIONS }
} = appConfig;

const termsData = {
	heading: "TERMS.HEADING",
	subHeading: "TERMS.SUB_HEADING",
	points: [
		"TERMS.POINT_1",
		"TERMS.POINT_2",
		"TERMS.POINT_3",
		"TERMS.POINT_4",
		"TERMS.POINT_5",
		"TERMS.POINT_6",
		"TERMS.POINT_7",
		"TERMS.POINT_8"
	],
	keywords: ["TERMS.KEYWORD_1", "TERMS.KEYWORD_2", "TERMS.KEYWORD_3", "TERMS.KEYWORD_4"],
	hyperlinks: [
		AWS_CUSTOMER_AGREEMENT,
		AWS_ACCEPTABLE_USE_POLICY,
		AWS_PRIVACY_NOTICE,
		AMAZON_LOCATION_TERMS_AND_CONDITIONS
	]
};

export default termsData;
